"""initial schema

Revision ID: 77619896af41
Revises: 
Create Date: 2026-09-08 20:43:35.409491
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '77619896af41'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('shop_id', sa.Text(), nullable=True),
    sa.Column('shop_domain', sa.Text(), nullable=True),
    sa.Column('widget_public_key', sa.Text(), nullable=True),
    sa.Column('widget_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('widget_allowed_origins', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('widget_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tenants_shop_domain_key', 'tenants', ['shop_domain'], unique=True, postgresql_where=sa.text('shop_domain is not null'))
    op.create_index('tenants_shop_domain_widget_public_key_idx', 'tenants', ['shop_domain', 'widget_public_key'], unique=False)
    op.create_index('tenants_shop_id_key', 'tenants', ['shop_id'], unique=True, postgresql_where=sa.text('shop_id is not null'))
    op.create_index('tenants_widget_public_key_key', 'tenants', ['widget_public_key'], unique=True, postgresql_where=sa.text('widget_public_key is not null'))
    op.create_table('agent_tools',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('read_only', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('read_only', name='agent_tools_read_only_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('agent_tools_tenant_id_name_key', 'agent_tools', ['tenant_id', 'name'], unique=True)
    op.create_index('agent_tools_tenant_id_read_only_idx', 'agent_tools', ['tenant_id', 'read_only'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('roas', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('revenue >= 0', name='campaigns_revenue_check'),
    sa.CheckConstraint('roas >= 0', name='campaigns_roas_check'),
    sa.CheckConstraint('spend >= 0', name='campaigns_spend_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('campaigns_tenant_id_channel_idx', 'campaigns', ['tenant_id', 'channel'], unique=False)
    op.create_index('campaigns_tenant_id_created_at_idx', 'campaigns', ['tenant_id', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('external_product_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('public_visible', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('active', 'inactive', 'archived')", name='products_status_check'),
    sa.CheckConstraint('price is null or price >= 0', name='products_price_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('products_tenant_id_category_idx', 'products', ['tenant_id', 'category'], unique=False)
    op.create_index('products_tenant_id_external_product_id_key', 'products', ['tenant_id', 'external_product_id'], unique=True, postgresql_where=sa.text('external_product_id is not null'))
    op.create_index('products_tenant_id_public_visible_idx', 'products', ['tenant_id', 'public_visible'], unique=False)
    op.create_index('products_tenant_id_status_idx', 'products', ['tenant_id', 'status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('store_owner', 'marketing_manager', 'team_member', 'admin')", name='users_role_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_user_id', name='users_auth_user_id_key'),
    sa.UniqueConstraint('tenant_id', 'email', name='users_tenant_id_email_key')
    )
    op.create_index('users_tenant_id_role_idx', 'users', ['tenant_id', 'role'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('surface', sa.Text(), nullable=False),
    sa.Column('visitor_id', sa.Text(), nullable=True),
    sa.Column('shop_domain', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('active', 'archived')", name='conversations_status_check'),
    sa.CheckConstraint("surface in ('dashboard', 'widget')", name='conversations_surface_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('conversations_tenant_id_status_idx', 'conversations', ['tenant_id', 'status'], unique=False)
    op.create_index('conversations_tenant_id_surface_created_at_idx', 'conversations', ['tenant_id', 'surface', 'created_at'], unique=False)
    op.create_index('conversations_tenant_id_user_id_created_at_idx', 'conversations', ['tenant_id', 'user_id', 'created_at'], unique=False)
    op.create_index('conversations_tenant_id_visitor_id_idx', 'conversations', ['tenant_id', 'visitor_id'], unique=False, postgresql_where=sa.text('visitor_id is not null'))
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Text(), server_default=sa.text("'internal'"), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('uploaded', 'processing', 'ready', 'failed')", name='documents_status_check'),
    sa.CheckConstraint("type in ('pdf', 'docx', 'txt', 'markdown', 'notion', 'web', 'csv')", name='documents_type_check'),
    sa.CheckConstraint("visibility in ('internal', 'public')", name='documents_visibility_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('documents_tenant_id_created_at_idx', 'documents', ['tenant_id', 'created_at'], unique=False)
    op.create_index('documents_tenant_id_status_idx', 'documents', ['tenant_id', 'status'], unique=False)
    op.create_index('documents_tenant_id_type_idx', 'documents', ['tenant_id', 'type'], unique=False)
    op.create_index('documents_tenant_id_visibility_idx', 'documents', ['tenant_id', 'visibility'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending', 'paid', 'fulfilled', 'cancelled', 'refunded')", name='orders_status_check'),
    sa.CheckConstraint('total_amount >= 0', name='orders_total_amount_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('orders_tenant_id_created_at_idx', 'orders', ['tenant_id', 'created_at'], unique=False)
    op.create_index('orders_tenant_id_status_idx', 'orders', ['tenant_id', 'status'], unique=False)
    op.create_index('orders_tenant_id_user_id_idx', 'orders', ['tenant_id', 'user_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'permission', name='permissions_tenant_id_user_id_permission_key')
    )
    op.create_index('permissions_tenant_id_permission_idx', 'permissions', ['tenant_id', 'permission'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Text(), nullable=False),
    sa.Column('chroma_collection', sa.Text(), nullable=False),
    sa.Column('chroma_vector_id', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility in ('internal', 'public')", name='document_chunks_visibility_check'),
    sa.CheckConstraint('chunk_index >= 0', name='document_chunks_chunk_index_check'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chroma_vector_id', name='document_chunks_chroma_vector_id_key'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='document_chunks_document_id_chunk_index_key')
    )
    op.create_index('document_chunks_tenant_id_document_id_idx', 'document_chunks', ['tenant_id', 'document_id'], unique=False)
    op.create_index('document_chunks_tenant_id_visibility_idx', 'document_chunks', ['tenant_id', 'visibility'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('used_tools', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sender in ('user', 'customer', 'assistant', 'system')", name='messages_sender_check'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('messages_tenant_id_conversation_id_created_at_idx', 'messages', ['tenant_id', 'conversation_id', 'created_at'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='sales_amount_check'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('sales_tenant_id_created_at_idx', 'sales', ['tenant_id', 'created_at'], unique=False)
    op.create_index('sales_tenant_id_order_id_idx', 'sales', ['tenant_id', 'order_id'], unique=False)
    op.create_index('sales_tenant_id_product_id_idx', 'sales', ['tenant_id', 'product_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('surface', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("surface in ('dashboard', 'widget')", name='feedback_surface_check'),
    sa.CheckConstraint('rating between 1 and 5', name='feedback_rating_check'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('feedback_tenant_id_message_id_idx', 'feedback', ['tenant_id', 'message_id'], unique=False)
    op.create_index('feedback_tenant_id_surface_created_at_idx', 'feedback', ['tenant_id', 'surface', 'created_at'], unique=False)
    op.create_index('feedback_tenant_id_user_id_created_at_idx', 'feedback', ['tenant_id', 'user_id', 'created_at'], unique=False, postgresql_where=sa.text('user_id is not null'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('feedback_tenant_id_user_id_created_at_idx', table_name='feedback', postgresql_where=sa.text('user_id is not null'))
    op.drop_index('feedback_tenant_id_surface_created_at_idx', table_name='feedback')
    op.drop_index('feedback_tenant_id_message_id_idx', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('sales_tenant_id_product_id_idx', table_name='sales')
    op.drop_index('sales_tenant_id_order_id_idx', table_name='sales')
    op.drop_index('sales_tenant_id_created_at_idx', table_name='sales')
    op.drop_table('sales')
    op.drop_index('messages_tenant_id_conversation_id_created_at_idx', table_name='messages')
    op.drop_table('messages')
    op.drop_index('document_chunks_tenant_id_visibility_idx', table_name='document_chunks')
    op.drop_index('document_chunks_tenant_id_document_id_idx', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('permissions_tenant_id_permission_idx', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('orders_tenant_id_user_id_idx', table_name='orders')
    op.drop_index('orders_tenant_id_status_idx', table_name='orders')
    op.drop_index('orders_tenant_id_created_at_idx', table_name='orders')
    op.drop_table('orders')
    op.drop_index('documents_tenant_id_visibility_idx', table_name='documents')
    op.drop_index('documents_tenant_id_type_idx', table_name='documents')
    op.drop_index('documents_tenant_id_status_idx', table_name='documents')
    op.drop_index('documents_tenant_id_created_at_idx', table_name='documents')
    op.drop_table('documents')
    op.drop_index('conversations_tenant_id_visitor_id_idx', table_name='conversations', postgresql_where=sa.text('visitor_id is not null'))
    op.drop_index('conversations_tenant_id_user_id_created_at_idx', table_name='conversations')
    op.drop_index('conversations_tenant_id_surface_created_at_idx', table_name='conversations')
    op.drop_index('conversations_tenant_id_status_idx', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('users_tenant_id_role_idx', table_name='users')
    op.drop_table('users')
    op.drop_index('products_tenant_id_status_idx', table_name='products')
    op.drop_index('products_tenant_id_public_visible_idx', table_name='products')
    op.drop_index('products_tenant_id_external_product_id_key', table_name='products', postgresql_where=sa.text('external_product_id is not null'))
    op.drop_index('products_tenant_id_category_idx', table_name='products')
    op.drop_table('products')
    op.drop_index('campaigns_tenant_id_created_at_idx', table_name='campaigns')
    op.drop_index('campaigns_tenant_id_channel_idx', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('agent_tools_tenant_id_read_only_idx', table_name='agent_tools')
    op.drop_index('agent_tools_tenant_id_name_key', table_name='agent_tools')
    op.drop_table('agent_tools')
    op.drop_index('tenants_widget_public_key_key', table_name='tenants', postgresql_where=sa.text('widget_public_key is not null'))
    op.drop_index('tenants_shop_id_key', table_name='tenants', postgresql_where=sa.text('shop_id is not null'))
    op.drop_index('tenants_shop_domain_widget_public_key_idx', table_name='tenants')
    op.drop_index('tenants_shop_domain_key', table_name='tenants', postgresql_where=sa.text('shop_domain is not null'))
    op.drop_table('tenants')
    # ### end Alembic commands ###
